"""delete foo and bar in users table

Revision ID: ff2991124eed
Revises: d4f7402784ac
Create Date: 2025-12-03 13:15:24.289468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff2991124eed"
down_revision: Union[str, Sequence[str], None] = "d4f7402784ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_foo_bar"), "users", type_="unique")
    op.drop_column("users", "bar")
    op.drop_column("users", "foo")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("foo", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("bar", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_users_foo_bar"),
        "users",
        ["foo", "bar"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
